FROM quay.io/wildfly/wildfly:35.0.1.Final-jdk17

# add deployment archive.
ADD ./target/*.war /opt/jboss/wildfly/standalone/deployments/

# add admin users
#RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone-full.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
