name: arq-wildfly-remote

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "maven"
      - name: Run WildFly server
        run: |
          export WF_ARCHIVE=wildfly
          export WF_VERSION=28.0.1.Final
          export INSTALL_DIR="/opt/appsvr"
          mkdir ${INSTALL_DIR}

          curl -o /tmp/${WF_ARCHIVE}.zip -L https://github.com/wildfly/wildfly/releases/download/${WF_VERSION}/wildfly-${WF_VERSION}.zip \
              && unzip /tmp/${WF_ARCHIVE}.zip -d ${INSTALL_DIR} \
              && rm /tmp/${WF_ARCHIVE}.zip \
              && true

          chmod -R a+rw ${INSTALL_DIR}
          chmod -R a+x ${INSTALL_DIR}/${WF_ARCHIVE}-${WF_VERSION}/bin/*
          export WF_HOME=${INSTALL_DIR}/${WF_ARCHIVE}-${WF_VERSION}
          ${WF_HOME}/bin/add-user.sh admin Admin@123 --silent
          ${WF_HOME}/bin/standalone.sh -c standalone-full.xml &
          sleep 10

      - name: Build with Maven
        run: mvn clean verify -Parq-wildfly-remote
